/*
 * This source file was generated by the Gradle 'init' task
 */
package com.furnituredesigner;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test 
    public void appLaunchesWithoutError() {
        // Simple test to verify the App class can be instantiated
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "App class should be instantiable");
    }
}
